### ISSUE TITLE
Add OreDict support for the inputs of the two machines

### ISSUE THREAD

**Issue by ChromaPIE** [Cosmoledo/NuclearCraft_Helper#2]
When in a pack containing both NuclearCraft and GregTech CE, when giving GTCE a bigger priority some isotopes like U-235 or Pu-241 or more would be transformed into GTCE ones. Well it's also easy to change the priority, but maybe it's better to accept items depending on OreDict.

**Comment by Cosmoledo** [comment]
Hey, thanks for your issue. I have never played the mod GregTech. I have made some changes, could you check [this version](https://github.com/Cosmoledo/NuclearCraft_Helper/files/4629290/NuclearCraft_Helper-1.0.2.jar.zip)? In my research I detected that only U-235 and Pu-241 can be crafted into NuclearCraft items, right? So only the Tiny Compactor uses them?

**Comment by ChromaPIE** [comment]
![image](https://user-images.githubusercontent.com/56111366/82014571-74213d00-96af-11ea-85d1-98c49ea9dd2c.png)
![image](https://user-images.githubusercontent.com/56111366/82014582-78e5f100-96af-11ea-91cf-ed50c97a3f74.png)

Works pretty good! Thank you!

So far these are the only two which otherwise can be able to put in the Helpers only after transformed by Mekanism's Oredictionificator. Now it became more convenient.

BTW could you make the helpers larger to contain more kinds of isotopes or make items in it 64+ stackable by making upgrades or something? As players always want to get the best fuels from the materials one has. Restricted by the storage, or even because there are just two or three more U-238s in it (You know U-238 always stacks), there would be less space for advanced isotopes, Americium, Californium, stuff like that. As you can see in the screenshots, my helpers are both full, and I have to left some of them outside. It seems not good for calculating what can I make now, nor for the automation.

**Comment by Cosmoledo** [comment]
I'm happy to hear that it works. Thank you.

Yeah, it was a good idea to change the size of the inventory, I have done that. Check [Version 1.0.3](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-helper/files/2957470), but read the changelog.
