### ISSUE TITLE
Rotating helpers with wrenches causing all contents disappear

### ISSUE THREAD

**Issue by ChromaPIE** [Cosmoledo/NuclearCraft_Helper#3]
Happened with the wrench in Thermal Foundation and the rotated one is the Fuel Crafter, probably the compactor has the same problem, anyway it's not tested.

**Comment by Cosmoledo** [comment]
Thank you, I have never tested that. So I am happy that your PC did not explode :) I'm on it.

**Comment by Cosmoledo** [comment]
Hey, I was able to fix the bug. https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-helper/files/2971595
